name: CI/CD

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: AhmetB-Dev/django-devops-template/.github/workflows/reusable-ci.yml@main

  publish:
    name: Publish image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ci
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: AhmetB-Dev/django-devops-template/.github/workflows/reusable-publish.yml@main

  deploy:
    name: Deploy production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: publish
    permissions:
      contents: read
      packages: read
    uses: AhmetB-Dev/django-devops-template/.github/workflows/reusable-deploy.yml@main
    with:
      environment: production
      image: ${{ needs.publish.outputs.image }}:sha-${{ github.sha }}
